all:  master

MasterBozzaModificato27Dic.o : UtenteBozzaModificato27Dic.o NodoBozzaModificato27Dic.o

master: MasterBozzaModificato27Dic.c UtenteBozzaModificato27Dic.c NodoBozzaModificato27Dic.c
	gcc MasterBozzaModificato27Dic.c  -o master 

run:  all
	./master

clean: 
	rm master